import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Interface for user data
export interface UserData { // Export UserData interface
    name: string;
    email: string;
    phoneNumber: number;
}
// Function to get user data from localStorage
function getUserData(): UserData {
    const user = window.localStorage.getItem("user");
    return user ? JSON.parse(user) : { name: "", email: "", phoneNumber: 0 };
}

// Initial state
const initialState: UserData = getUserData();

// Create the user slice
export const userSlice = createSlice({
    name: 'user',
    initialState,
    reducers: {
        setUser: (state, action: PayloadAction<UserData>) => {
            const { name, email, phoneNumber } = action.payload;
            state.name = name;
            state.email = email;
            state.phoneNumber = phoneNumber;
            // Save user data to localStorage
            window.localStorage.setItem("user", JSON.stringify(state));
        },
        logOutUser: (state) => {
            // Clear user data from state
            state.name = "";
            state.email = "";
            state.phoneNumber = 0;
            // Remove user data from localStorage
            window.localStorage.removeItem("user");
        },
    },
});

// Export the actions generated by createSlice
export const { setUser, logOutUser } = userSlice.actions;

// Export the reducer to be included in the store
export default userSlice.reducer;
